name: CI

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main", "develop"]

permissions:
  contents: read
  packages: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "npm"
          registry-url: "https://npm.pkg.github.com"
          scope: "@dat-21"

      - name: Verify GitHub Packages auth
        run: npm whoami --registry=https://npm.pkg.github.com
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}

      - name: Install dependencies
        run: npm ci
        # Set the NODE_AUTH_TOKEN environment variable to authenticate with GitHub Packages
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build
        env:
          VITE_API_URL: http://localhost:5000
